{
 "title": "数据库信息",
 "tags": [ "tesla" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "car_id",
    "label": "车辆",
    "query": "SELECT\n    id as __value,\n    CASE WHEN COUNT(id) OVER (PARTITION BY name) > 1 AND name IS NOT NULL THEN CONCAT(name, ' - ', RIGHT(vin, 6)) ELSE COALESCE(name, CONCAT('VIN ', vin)) end as __text \nFROM cars\nORDER BY display_priority ASC, name ASC, vin ASC;"
   },
   {
    "name": "pg_stat_statements_info_last_reset",
    "query": "SELECT\n    CASE WHEN $pg_stat_statements_enabled = 1 THEN 'SELECT stats_reset FROM pg_stat_statements_info;' else 'SELECT NULL;' end"
   },
   {
    "name": "pg_stat_statements_count",
    "query": "SELECT\n    CASE WHEN $pg_stat_statements_enabled = 1 THEN 'SELECT count(*) FROM pg_stat_statements;' else 'SELECT NULL;' end"
   },
   {
    "name": "pg_stat_statements_top_20_mean",
    "query": "SELECT\n    CASE WHEN $pg_stat_statements_enabled = 1 THEN 'select\n  calls as \"调用次数\",\n  mean_exec_time as \"平均执行时间\",\n  total_exec_time as \"总执行时间\",\n  query as \"查询语句\"\nfrom pg_stat_statements\nORDER BY mean_exec_time desc\nlimit 20;' else 'SELECT NULL;' end"
   },
   {
    "name": "pg_stat_statements_top_20_total",
    "query": "SELECT\n    CASE WHEN $pg_stat_statements_enabled = 1 THEN 'select\n  calls as \"调用次数\",\n  mean_exec_time as \"平均执行时间\",\n  total_exec_time as \"总执行时间\",\n  query as \"查询语句\"\nfrom pg_stat_statements\nORDER BY total_exec_time desc\nlimit 20;' else 'SELECT NULL;' end"
   },
   {
    "name": "pg_stat_statements_enabled",
    "query": "SELECT EXISTS (\nSELECT 1\nFROM information_schema.tables\nWHERE table_name = 'pg_stat_statements'\n)::int AS table_existence"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "里程统计",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ROUND(convert_km(sum(distance)::numeric, '$length_unit'), 0) || ' $length_unit' as \"已记录里程\",\n  ROUND(convert_km(max(end_km)::numeric, '$length_unit'), 0) || ' $length_unit' as \"总里程表\"\nfrom drives where car_id = $car_id;"
    }
   ]
  },
  {
   "title": "统计信息",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) AS \"充电次数\" FROM charging_processes WHERE car_id=$car_id \n"
    },
    {
     "rawSql": "SELECT COUNT(id) AS \"行驶次数\" FROM drives WHERE car_id=$car_id "
    }
   ]
  },
  {
   "title": "软件信息",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as \"车辆更新次数\"\nFROM Updates \nWHERE car_id = $car_id\n"
    },
    {
     "rawSql": "select split_part(version, ' ', 1) as \"当前车辆固件版本\" \r\nfrom updates \r\nwhere car_id = $car_id \r\norder by start_date desc \r\nlimit 1"
    }
   ]
  },
  {
   "title": "不完整数据",
   "type": "stat",
   "description": "这意味着您有一些**行驶记录**或**充电记录**未关闭。\n如果是这样，您可以按照官方指南操作：\n<a href='https://docs.teslamate.org/docs/maintenance/manually_fixing_data' target='_blank'>手动修复数据</a>",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) as \"未关闭的充电记录\"\nFROM charging_processes \nWHERE car_id = $car_id AND end_date is null\n"
    },
    {
     "rawSql": "SELECT COUNT(id) AS \"未关闭的行驶记录\"\r\nFROM drives \r\nWHERE car_id = $car_id AND end_date is null"
    }
   ]
  },
  {
   "title": "PostgreSQL版本",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT regexp_replace(version(), 'PostgreSQL ([^ ]+) .*', '\\1') AS version;"
    }
   ]
  },
  { "title": "数据库信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n   relname AS \"表名\",\r\n   pg_relation_size(relid) as \"数据大小\",\r\n   pg_indexes_size(relid) as \"索引大小\",\r\n   pg_total_relation_size(relid) As \"总大小\"\r\nFROM \r\n   pg_catalog.pg_statio_user_tables\r\nORDER BY \r\n   pg_total_relation_size(relid) DESC;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 4, "x": 6, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT table_name AS \"表名\", \r\n       (xpath('/row/cnt/text()', xml_count))[1]::text::int AS \"行数\"\r\nFROM (\r\n    SELECT table_name, \r\n           query_to_xml(format('SELECT count(*) as cnt FROM %I.%I', table_schema, table_name), false, true, '') AS xml_count\r\n    FROM information_schema.tables\r\n    WHERE table_schema NOT IN ('pg_catalog', 'information_schema') and table_type = 'BASE TABLE'\r\n) AS t\r\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "索引信息",
   "type": "table",
   "description": "这些统计信息可以帮助您评估索引的效率。\n\n如果您的数据库经历大量更新或删除操作，比如从其他来源导入数据或删除借用车辆等类似情况，您可能会遇到索引膨胀，这可能会降低性能。在这种情况下，重新索引可能会有所帮助。\n\n查看 <a href='https://docs.teslamate.org/docs/maintenance/manually_fixing_data#reindex-database' target='_blank'>重新索引数据库</a>",
   "gridPos": { "h": 19, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    relname AS \"表名\",\r\n    indexrelname AS \"索引\",\r\n    idx_scan AS \"索引扫描次数\",\r\n    idx_tup_read AS \"读取的元组\",\r\n    idx_tup_fetch AS \"获取的元组\",\r\n    PG_RELATION_SIZE(indexrelid) as \"索引大小\"\r\nFROM\r\n    pg_stat_all_indexes\r\nWHERE\r\n    schemaname NOT LIKE 'pg_%' AND\r\n    indexrelname IS NOT NULL\r\nORDER BY 3 DESC;"
    }
   ]
  },
  {
   "title": "数据库总大小",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(pg_total_relation_size(relid)) As \"大小\"\nFROM \n    pg_catalog.pg_statio_user_tables;"
    }
   ]
  },
  {
   "title": "时区",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "show timezone;" }
   ]
  },
  { "title": "SQL计划与执行统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "pg_stat_statements视图中所有统计信息最后一次重置的时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "${pg_stat_statements_info_last_reset:raw}"
    }
   ]
  },
  {
   "title": "通过pg_stat_statements跟踪的语句数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "rawSql": "${pg_stat_statements_count:raw}"
    }
   ]
  },
  {
   "title": "关于pg_stat_statements(跟踪SQL计划与执行的统计信息)",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "options": {
    "content": "查看[贡献文档](https://docs.teslamate.org/docs/development#enable-pg_stat_statements-to-collect-query-statistics)了解如何启用跟踪服务器执行的所有SQL语句的计划和执行统计。\n"
   }
  },
  {
   "title": "前20条语句(按语句执行平均时间排序)",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "${pg_stat_statements_top_20_mean:raw}"
    }
   ]
  },
  {
   "title": "前20条语句(按语句执行总时间排序)",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "${pg_stat_statements_top_20_total:raw}"
    }
   ]
  }
 ]
}